### ISSUE TITLE
Image optimisation for performance

### ISSUE THREAD

**Issue by kdevnel** [bradleymubenga777/bradleymubenga#12]
Some of the images could be resized and compressed using something like compressor.io in order to improve loading speed and site size without compromising quality.

In particular, this image is over 5mb in size - https://bradleymubenga.co.za/static/media/space-events-website-showcase-1.c9368c4d.jpeg

Overall the performance is great so this would make a huge difference. Here is a GTMetrix report to make you feel good! https://gtmetrix.com/reports/bradleymubenga.co.za/jkfn3Lrw/

**Comment by bradleymubenga777** [comment]
@kdevnel Compressed the image, loading time went from 1.6s to 1.5s. Is it a good improvement or should I aim for more optimization or a CDN?

**Comment by kdevnel** [comment]
The optimisation is good. It's a small step but it's a good step. I would agree that some sort of CDN is always good if you can set it up and also caching would be good but to be honest - this is just polishing something that is already good 👍🏻
